name: fetch changefile
on:
  push:
    paths:
      - '**.md'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: 
        uses: action/checkout@v3
        with:
          fetch-depth: 2